openapi: 3.1.0
info:
  title: Survey Service
  version: "1.0"
paths:
  /api/user/register:
    summary: Register a new user
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: Successfully registered new user, returns JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
