openapi: 3.1.0
info:
  title: Survey Service
  version: "1.0"
paths:
  /api/user/register:
    summary: Register a new user
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginParams"
      responses:
        "201":
          description: Successfully registered new user, returns JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
  /api/user/login:
    summary: Log in an existing user
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginParams"
      responses:
        "200":
          description: Successfully logged in user, returns JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
  "/api/survey/{survey}":
    parameters:
      - in: path
        name: survey
        required: true
        schema:
          type: string
    patch:
      responses:
        "200":
          description: The survey was updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                title:
                  type: string
                published:
                  type: boolean
                questions:
                  type: array
                  items: {}
components:
  schemas:
    UserLoginParams:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
