openapi: 3.1.0
info:
  title: Survey Service
  version: "1.0"
paths:
  /api/user/register:
    summary: Register a new user
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginParams"
      responses:
        "201":
          description: Successfully registered new user, returns JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
  /api/user/login:
    summary: Log in an existing user
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginParams"
      responses:
        "200":
          description: Successfully logged in user, returns JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                required:
                  - token
  "/api/survey/{survey}":
    parameters:
      - $ref: "#/components/parameters/survey"
    get:
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  description:
                    type: string
                  published:
                    type: boolean
                  owner_id:
                    type: number
                  questions:
                    type: array
                    items:
                      $ref: "#/components/schemas/SurveyQuestion"
                required:
                  - id
                  - title
                  - description
                  - published
                  - owner_id
                  - questions
        "403":
          description: Forbidden, survey is not published and you are not the owner
        "404":
          description: Survey not found
    post:
      responses:
        "200":
          description: 200 response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  description:
                    type: string
                  published:
                    type: boolean
                  owner_id:
                    type: number
                  questions:
                    type: array
                    items:
                      $ref: "#/components/schemas/SurveyQuestion"
                required:
                  - id
                  - title
                  - description
                  - published
                  - owner_id
                  - questions
    patch:
      summary: Update a survey
      description: |
        Update a survey. Only the owner of the survey can update it. If the survey is published, it cannot be updated unless it is unpublished first.

        The request body can contain any of the top level fields, but they are not required. If a field is not present, it will not be updated.
      responses:
        "200":
          description: The survey was updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                title:
                  type: string
                published:
                  type: boolean
                questions:
                  type: array
                  items:
                    $ref: "#/components/schemas/SurveyQuestion"
components:
  parameters:
    survey:
      name: survey
      in: path
      required: true
      description: The survey ID
      schema:
        type: string
  schemas:
    UserLoginParams:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    SurveyQuestion:
      type: object
      properties:
        uuid:
          type: string
        required:
          type: boolean
        question:
          $ref: "#/components/schemas/Question"
    Question:
      type: object
      properties:
        type:
          type: string
          enum:
            - Text
            - Rating
        content:
          oneOf:
            - $ref: "#/components/schemas/QText"
            - $ref: "#/components/schemas/QRating"
    QText:
      type: object
      properties:
        prompt:
          type: string
        description:
          type: string
        multiline:
          type: boolean
    QRating:
      type: object
      properties:
        prompt:
          type: string
        description:
          type: string
        max_rating:
          type: integer
