CREATE TABLE surveys (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL DEFAULT "",
	description TEXT NOT NULL DEFAULT "",
	published BOOLEAN NOT NULL DEFAULT FALSE,
	owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	questions JSONB NOT NULL DEFAULT '[]'::JSONB,
);