name: Node

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run check
      - run: yarn run lint
      - name: cargo-install
        uses: baptiste0928/cargo-install@v1
        with:
          crate: typeshare-cli
          version: "1.5.0"
      - name: Ensure generated files are up to date
        run: ./scripts/ensure-generated.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run test:unit
